import {saveProject,readProject,validateProject} from './project-store.mjs';
import {detectFace} from './alignment.mjs';
import {interpretScene} from './scene-events.mjs';
const $=s=>document.querySelector(s),canvas=$('#scene'),ctx=canvas.getContext('2d');
const worlds={cosmic:{top:'#251038',bottom:'#090916',color:'#ed55ca'},forest:{top:'#183c29',bottom:'#06160f',color:'#54d27b'},ocean:{top:'#073f62',bottom:'#061324',color:'#44cdeb'},desert:{top:'#764a32',bottom:'#241b25',color:'#efb46c'}};
let photo,body,sprites,world='cosmic',pan={x:0,y:0},playing=false,frame=0,lastFrame=0,source='supplied-reference-body',crop=null,lastEvent=null,photoVersion=0;
const controls=['zoom','rotation','blend','faceX','faceY','faceSize','influence'];const value=id=>Number($('#'+id).value);
function load(src){return new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(Error('Could not decode this image'));i.src=src})}
function download(blob,name){if(globalThis.NativeDownloads&&blob){const reader=new FileReader();reader.onload=()=>{NativeDownloads.save(name,blob.type||'application/json',String(reader.result).split(',')[1]);$('#saveStatus').textContent='Choose where to save your file.'};reader.onerror=()=>{$('#saveStatus').textContent='Could not prepare export.'};reader.readAsDataURL(blob);return}if(!blob){$('#saveStatus').textContent='Export failed: no image was produced.';return}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();$('#saveStatus').textContent='Download requested: '+name+'. Check your Downloads folder.';setTimeout(()=>URL.revokeObjectURL(url),60000)}
function face(c,w,h){if(!photo)return;const fw=w*value('faceSize'),fh=fw*1.26,x=w*value('faceX'),y=h*value('faceY');c.save();c.beginPath();c.ellipse(x,y,fw/2,fh/2,0,0,Math.PI*2);c.clip();c.globalAlpha=value('blend');c.translate(x,y);c.rotate(value('rotation')*Math.PI/180);const box=crop??{x:0,y:0,width:photo.width,height:photo.height};const scale=Math.max(fw/box.width,fh/box.height)*value('zoom');c.drawImage(photo,box.x,box.y,box.width,box.height,-box.width*scale/2+pan.x*fw,-box.height*scale/2+pan.y*fh,box.width*scale,box.height*scale);c.restore();}
function character(c,w,h,index=0){c.save();if(sprites){const cols=Math.max(1,Math.min(16,Number($('#cols').value)||1)),rows=Math.max(1,Math.min(16,Number($('#rows').value)||1)),sw=sprites.width/cols,sh=sprites.height/rows;c.drawImage(sprites,(index%cols)*sw,Math.floor(index/cols)*sh,sw,sh,0,0,w,h)}else if(body)c.drawImage(body,0,0,w,h);face(c,w,h);c.globalCompositeOperation='soft-light';c.globalAlpha=value('influence')*.55;c.fillStyle=worlds[world].color;c.fillRect(0,0,w,h);c.restore()}
function render(){const w=canvas.width,h=canvas.height,p=worlds[world];const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,p.top);g.addColorStop(1,p.bottom);ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.strokeStyle=p.color+'40';for(let i=0;i<6;i++){ctx.beginPath();ctx.ellipse(w*.5,h*.55,80+i*48,100+i*70,.4,0,Math.PI*2);ctx.stroke()}ctx.save();ctx.translate(170,45);character(ctx,380,870,frame);ctx.restore();ctx.fillStyle='#f3d4e8';ctx.font='14px system-ui';ctx.fillText('YOU-N-I-VERSE · '+world.toUpperCase(),25,925);}
async function upload(input,kind){const file=input.files[0];if(!file)return;const url=URL.createObjectURL(file);try{const image=await load(url);if(kind==='photo'){photo=image;photoVersion++;crop=null;pan={x:0,y:0};$('#align').disabled=false;$('#status').textContent='Photo mapped · drag to align your face';for(const id of ['save','recipe','atlas'])$('#'+id).disabled=false;if(sprites)$('#sheetSave').disabled=false}else if(kind==='body'){body=image;sprites=null;playing=false;source=file.name;$('#status').textContent='Custom body loaded · adjust face placement'}else{sprites=image;playing=false;frame=0;$('#animate').disabled=false;$('#sheetSave').disabled=!photo;$('#sheetStatus').textContent='Sheet loaded · face placement currently shared across frames'}render();if(kind==='photo')await alignPhoto();scheduleSave()}catch(e){$('#status').textContent=e.message}finally{URL.revokeObjectURL(url)}}
for(const id of ['photo','camera'])$('#'+id).onchange=()=>upload($('#'+id),'photo');$('#body').onchange=()=>upload($('#body'),'body');$('#sprites').onchange=()=>upload($('#sprites'),'sheet');for(const id of controls)$('#'+id).oninput=render;for(const id of ['cols','rows'])$('#'+id).oninput=()=>{frame=0;render()};
for(const b of document.querySelectorAll('[data-world]'))b.onclick=()=>{world=b.dataset.world;lastEvent=null;$('#eventStatus').textContent='Direct world preset · no Klein event recorded.';document.querySelectorAll('[data-world]').forEach(x=>x.classList.toggle('active',x===b));render()};
let drag;canvas.onpointerdown=e=>{if(!photo)return;drag={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!drag)return;const ratio=canvas.width/canvas.getBoundingClientRect().width,fw=380*value('faceSize');pan.x+=(e.clientX-drag.x)*ratio/fw;pan.y+=(e.clientY-drag.y)*ratio/fw;drag={x:e.clientX,y:e.clientY};render()};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;
$('#reset').onclick=()=>{pan={x:0,y:0};$('#zoom').value=1;$('#rotation').value=0;render()};$('#save').onclick=()=>canvas.toBlob(b=>download(b,'you-n-i-verse-character.png'));
$('#recipe').onclick=()=>download(new Blob([JSON.stringify({version:1,world,bodySource:source,controls:Object.fromEntries(controls.map(id=>[id,value(id)])),pan,faceCrop:crop,method:crop?'local-detected-face/surface-world-treatment':'manual-photo-ellipse/surface-world-treatment',photoIncluded:false,sceneEvent:lastEvent,canonicalStateBound:!!lastEvent},null,2)],{type:'application/json'}),'you-n-i-verse-morph-recipe.json');
$('#atlas').onclick=()=>{const sheet=document.createElement('canvas');sheet.width=720*4;sheet.height=960;const c=sheet.getContext('2d'),previous=world;Object.keys(worlds).forEach((name,i)=>{world=name;render();c.drawImage(canvas,i*720,0)});world=previous;render();sheet.toBlob(b=>download(b,'you-n-i-verse-world-variants.png'))};
$('#animate').onclick=()=>{playing=!playing;$('#animate').textContent=playing?'Pause sheet':'Play sheet'};$('#sheetSave').onclick=()=>{if(!sprites||!photo)return;const cols=Math.max(1,Math.min(16,Number($('#cols').value)||1)),rows=Math.max(1,Math.min(16,Number($('#rows').value)||1));const out=document.createElement('canvas');out.width=sprites.width;out.height=sprites.height;const c=out.getContext('2d');for(let i=0;i<cols*rows;i++){c.save();c.translate(i%cols*out.width/cols,Math.floor(i/cols)*out.height/rows);character(c,out.width/cols,out.height/rows,i);c.restore()}out.toBlob(b=>download(b,'you-n-i-verse-adapted-sprites.png'))};
function tick(t){if(!document.hidden&&playing&&sprites&&t-lastFrame>1000/value('fps')){const count=Math.max(1,Number($('#cols').value)*Number($('#rows').value));frame=(frame+1)%count;lastFrame=t;render()}requestAnimationFrame(tick)}
let saveTimer,saveQueue=Promise.resolve();
try{const reference=await load('assets/avatar-states.jpg');const crop=document.createElement('canvas');crop.width=320;crop.height=830;crop.getContext('2d').drawImage(reference,265,120,320,830,0,0,320,830);body=crop;render();await restoreSaved();requestAnimationFrame(tick)}catch(e){$('#status').textContent=e.message}

async function alignPhoto(){if(!photo)return;const version=photoVersion;$('#align').disabled=true;$('#alignment').textContent='Checking for a face locally…';const detection=await detectFace(photo);if(version!==photoVersion)return;if(detection.status==='detected'){crop=detection.crop;pan={x:0,y:0};$('#zoom').value=1;$('#rotation').value=0;$('#alignment').textContent='Face bounds detected locally. Adjust alignment if needed.';render()}else{$('#alignment').textContent={unsupported:'This browser has no local FaceDetector. Use the manual controls; no cloud request was made.',multiple:'Multiple faces found. Use a single-person portrait or align manually.',none:'No face detected. Manual alignment is available.',failed:'Local detection failed. Manual alignment is available.'}[detection.status]}$('#align').disabled=false}
$('#align').onclick=alignPhoto;
$('#executeScene').onclick=async()=>{const b=$('#executeScene');b.disabled=true;try{const r=await interpretScene($('#instruction').value);if(!r.ok){$('#eventStatus').textContent=r.reason;return}lastEvent=r.event;world=lastEvent.world;document.querySelectorAll('[data-world]').forEach(x=>x.classList.toggle('active',x.dataset.world===world));render();const record={...lastEvent,receipt:{applied:true,world,identitySourceUnchanged:true,effect:'surface-color-and-lighting'}};lastEvent=record;try{const key='you-n-i-verse-scene-events';const history=JSON.parse(localStorage.getItem(key)||'[]');history.push(record);localStorage.setItem(key,JSON.stringify(history));$('#eventStatus').textContent='Entered '+world+' · Klein lineage and five projections remembered.'}catch{$('#eventStatus').textContent='Entered '+world+' · storage unavailable; export the recipe to retain this event.'}}catch(e){$('#eventStatus').textContent=e.message}finally{b.disabled=false;scheduleSave()}};

function imageData(image){if(!image)return null;const c=document.createElement('canvas');c.width=image.naturalWidth||image.width;c.height=image.naturalHeight||image.height;c.getContext('2d').drawImage(image,0,0);return c.toDataURL('image/png')}
function snapshot(){return {type:'you-n-i-verse-project',version:1,savedAt:new Date().toISOString(),world,source,controls:Object.fromEntries(controls.map(id=>[id,value(id)])),pan:{...pan},crop,lastEvent,photo:imageData(photo),body:imageData(body),sprites:imageData(sprites),sheet:{cols:Number($('#cols').value),rows:Number($('#rows').value),fps:value('fps')}}}
async function restore(p){validateProject(p);const images=await Promise.all([p.photo?load(p.photo):null,p.body?load(p.body):null,p.sprites?load(p.sprites):null]);[photo,body,sprites]=images;world=p.world;source=p.source||'saved-body';pan={...p.pan};crop=p.crop??null;lastEvent=p.lastEvent??null;playing=false;frame=0;photoVersion++;for(const id of controls)$('#'+id).value=p.controls[id];for(const id of ['cols','rows','fps'])$('#'+id).value=p.sheet?.[id]??({cols:4,rows:3,fps:8}[id]);for(const id of ['save','recipe','atlas','align'])$('#'+id).disabled=!photo;$('#animate').disabled=!sprites;$('#sheetSave').disabled=!(sprites&&photo);document.querySelectorAll('[data-world]').forEach(x=>x.classList.toggle('active',x.dataset.world===world));$('#status').textContent=photo?'Saved character restored':'Saved studio restored';render()}
async function restoreSaved(){try{const p=await readProject();if(p){await restore(p);$('#saveStatus').textContent='Project restored from this device.'}else $('#saveStatus').textContent='Autosave ready on this device.'}catch(e){$('#saveStatus').textContent=e.message+'. Download a complete project to keep your work.'}}
function scheduleSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{saveQueue=saveQueue.catch(()=>{}).then(persist)},700)}
async function persist(){try{$('#saveStatus').textContent='Saving project…';await saveProject(snapshot());$('#saveStatus').textContent='Project saved on this device · '+new Date().toLocaleTimeString()}catch(e){$('#saveStatus').textContent='Could not save: '+e.message+'. Use Download complete project.'}}
$('#projectSave').onclick=()=>{clearTimeout(saveTimer);saveQueue=saveQueue.catch(()=>{}).then(persist)};$('#projectExport').onclick=()=>{try{download(new Blob([JSON.stringify(snapshot())],{type:'application/json'}),'you-n-i-verse-project.json')}catch(e){$('#saveStatus').textContent='Project export failed: '+e.message}};
$('#projectImport').onchange=async()=>{const f=$('#projectImport').files[0];if(!f)return;try{const p=validateProject(JSON.parse(await f.text()));await restore(p);await persist()}catch(e){$('#saveStatus').textContent='Could not open project: '+e.message}};
for(const id of controls)$('#'+id).addEventListener('input',scheduleSave);for(const id of ['cols','rows','fps'])$('#'+id).addEventListener('input',scheduleSave);for(const b of document.querySelectorAll('[data-world]'))b.addEventListener('click',scheduleSave);$('#reset').addEventListener('click',scheduleSave);canvas.addEventListener('pointerup',scheduleSave);canvas.addEventListener('pointercancel',scheduleSave);

window.addEventListener('native-save-result',e=>{$('#saveStatus').textContent=e.detail});
